[workspace]
members = ["programs/invariant", "programs/invariant/invariant-types"]
[profile.test]
overflow-checks = false

[profile.release]
# lto = "fat"
# codegen-units = 1
overflow-checks = true

# [profile.release.build-override]
# opt-level = 3
# incremental = false
# codegen-units = 1
